name: First Workflow

on: 
 push:
  branches:
    - master
 workflow_dispatch:
 
jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
  -  uses: actions/setup-java@v4.7.0
     with:
      java-version: '21'
      distribution: 'oracle'
