name: First Workflow

on: 
 issues:
 workflow_dispatch:
 
jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
   - run: echo 'Hello'
 job2:
  needs: job1
  runs-on: windows-latest
  steps:
    - run: echo 'Hello for windows'
